### ISSUE TITLE
Horses Health Compromise

### ISSUE THREAD

**Issue by Blackdeathy** [duke-tylerjone/gc-bugs-and-feedback#19]
At the moment horses are unarguably have a broken amount of hp then what they had before. It takes a almost 7 or more swings to take down a horse with a musket bayonet or sabre. This is really stupid and shouldn't be the case, also unrelated to this topic it also allows horses to tank bullets for the rider the majority of time. ///// Now After all this why not just revert the health of the old horse it would take 2 cavalry boosted swings to take a horse down. This version was too weak and almost anything could have taken down the horse (Please note that flying off the horse was a indirect buff to the Survivability of a rider since it would fling them away from where there horse died and where someone waiting with a bayonet or sword) It would just kill the horse and put them the majority of the time in the middle of a group of people. This is one of the various ways a rider would die other then other Riders.

There needs to be a reasonable health reduction of the horse and not to a degree where a scratch would spell the doom of a rider. I also believe with this compromise there should be a tweak where after the rider's horse has died he can go back to spawn for a new one. (The timer would be increased or left the same depending on how the developers (Tyler) See fit). or there can be no getting a new horse after the old one has died. And it would just be a health tweak. 

This is only my idea and can be added onto.  

Last notes: Horse duplication shouldn't be a problem since the a new horse would only be available once the owners previous horse has died. This will also give a better reason to chase down unmounted players instead of leaving them so they cant respawn with a new horse once they died. 

(Part of Last notes) If the rider has not died and the horse hasn't meaning he dismounted or just flat out died in which case the horse would run away so it would have been he dismounted. The previous horse would still be there but in his new life the whole process would start again meaning there would be no bullshit with his horse dying and then he would have to die since he couldn't spawn a new horse since the one in his previous life is still alive. The reason I don't agree with horses despawning is that I think it should be a new resource everytime on the battle field so if your horse dies in the thick of the fight you don't have to run all the way back to spawn to get a new horse and instead you would get a horse with lower health and of different speeds or class.

||||||||| If I have left anything out or you have a good idea please add it into the comments since any discussion helps a community thrive, DON'T BE NEGATIVE IN THE COMMENTS IF YOU DISAGREEE DON'T BE A ASS ABOUT IT |||||||||

(I am not biased towards infantry since I have had a lot of experience in both infantry and cavalry. I am currently a Cavalier in the dragoons where I am trying out a heavy cav)

THIS IS A SUGGESTION

**Comment by duke-tylerjone** [comment]
As I plan to redo horses entirely within the coming month, there is a good chance nothing will change for the time being.
